# This rule is not used by the project renovate-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to renovate.thegeeklab.de resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: renovate-operator
    app.kubernetes.io/managed-by: kustomize
  name: gitrepo-viewer-role
rules:
  - apiGroups:
      - renovate.thegeeklab.de
    resources:
      - gitrepos
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - renovate.thegeeklab.de
    resources:
      - gitrepos/status
    verbs:
      - get
