---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - renovate.thegeeklab.de
  resources:
  - gitrepos
  - renovators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - renovate.thegeeklab.de
  resources:
  - gitrepos/finalizers
  - renovators/finalizers
  verbs:
  - update
- apiGroups:
  - renovate.thegeeklab.de
  resources:
  - gitrepos/status
  - renovators/status
  verbs:
  - get
  - patch
  - update
