---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - renovate.thegeeklab.de
  resources:
  - discoveries
  - renovators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - renovate.thegeeklab.de
  resources:
  - discoveries/finalizers
  - renovators/finalizers
  verbs:
  - update
- apiGroups:
  - renovate.thegeeklab.de
  resources:
  - discoveries/status
  - renovators/status
  verbs:
  - get
  - patch
  - update
