apiVersion: renovate.thegeeklab.de/v1beta1
kind: Renovator
metadata:
  labels:
    app.kubernetes.io/name: renovate-operator
    app.kubernetes.io/managed-by: kustomize
  name: renovator-sample
spec:
  suspend: false
  schedule: "*/30 * * * *"

  discovery:
    suspend: false
    filter:
      - "octocat/*"

  logging:
    level: debug

  worker:
    strategy: batch
    instances: 1
    batchSize: 15

  renovate:
    platform:
      type: "gitea"
      endpoint: https://gitea.example.com/api/v1
      token:
        secretKeyRef:
          name: "my-secret"
          key: "platform_token"

    dryRun: true
    onboarding: true

    githubToken:
      secretKeyRef:
        name: "my-secret"
        key: "github_token"
